### ISSUE TITLE
Yolo version to openvino easy covertible

### ISSUE THREAD

**Issue by mastermind45** [THINK989/Automatic_License_Plate_Detector_for_Adverse_Environments#1]
Hi, wich yolov5 relase did you use? if you train on yolov5 relase v2.0 you can easy covet to openvino framework.

**Comment by THINK989** [comment]
Hi @mastermind45 
I have used the first version of YoloV5. I have been a little busy lately and wasn't keeping track of any update to the yolov5 model, thank you for an update though I will look into it and make all the changes as soon as possible.
